<?xml version="1.0" encoding="utf-8"?><Database Name="StreamingVideo" Class="DataClassesStreamingVideoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-QFKG2OF9;Initial Catalog=StreamingVideo;Integrated Security=True" SettingsObjectName="StreaminVideoApplication.Properties.Settings" SettingsPropertyName="StreamingVideoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ABBONAMENTO" Member="ABBONAMENTOs">
    <Type Name="ABBONAMENTO">
      <Column Name="codAbbonamento" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dataInizio" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="prezzo" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CF" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="ABBONAMENTO_PAGAMENTO" Member="PAGAMENTOs" ThisKey="codAbbonamento" OtherKey="codAbbonamento" Type="PAGAMENTO" />
      <Association Name="TITOLARE_ACCOUNT_ABBONAMENTO" Member="TITOLARE_ACCOUNT" ThisKey="CF" OtherKey="CF" Type="TITOLARE_ACCOUNT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VISIONE" Member="VISIONEs">
    <Type Name="VISIONE">
      <Column Name="nomeAccount" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nomeUtente" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="data" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ora" Type="System.TimeSpan" DbType="Time NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="minutoArrivo" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="codEpisodio" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="codFilm" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="EPISODIO_VISIONE" Member="EPISODIO" ThisKey="codEpisodio" OtherKey="codEpisodio" Type="EPISODIO" IsForeignKey="true" />
      <Association Name="FILM_VISIONE" Member="FILM" ThisKey="codFilm" OtherKey="codFilm" Type="FILM" IsForeignKey="true" />
      <Association Name="UTENTE_VISIONE" Member="UTENTE" ThisKey="nomeAccount,nomeUtente" OtherKey="nomeAccount,nomeUtente" Type="UTENTE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ACCOUNT" Member="ACCOUNTs">
    <Type Name="ACCOUNT">
      <Column Name="nomeAccount" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="ACCOUNT_TITOLARE_ACCOUNT" Member="TITOLARE_ACCOUNTs" ThisKey="nomeAccount" OtherKey="nomeAccount" Type="TITOLARE_ACCOUNT" />
      <Association Name="ACCOUNT_UTENTE" Member="UTENTEs" ThisKey="nomeAccount" OtherKey="nomeAccount" Type="UTENTE" />
    </Type>
  </Table>
  <Table Name="dbo.appartenere_ep" Member="appartenere_eps">
    <Type Name="appartenere_ep">
      <Column Name="codGenere" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codEpisodio" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="EPISODIO_appartenere_ep" Member="EPISODIO" ThisKey="codEpisodio" OtherKey="codEpisodio" Type="EPISODIO" IsForeignKey="true" />
      <Association Name="GENERE_appartenere_ep" Member="GENERE" ThisKey="codGenere" OtherKey="codGenere" Type="GENERE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.appartenere_film" Member="appartenere_films">
    <Type Name="appartenere_film">
      <Column Name="codGenere" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codFilm" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="FILM_appartenere_film" Member="FILM" ThisKey="codFilm" OtherKey="codFilm" Type="FILM" IsForeignKey="true" />
      <Association Name="GENERE_appartenere_film" Member="GENERE" ThisKey="codGenere" OtherKey="codGenere" Type="GENERE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CASA_PRODUTTRICE" Member="CASA_PRODUTTRICEs">
    <Type Name="CASA_PRODUTTRICE">
      <Column Name="codCasaProduttrice" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="annoFondazione" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CASA_PRODUTTRICE_produrre_ep" Member="produrre_eps" ThisKey="codCasaProduttrice" OtherKey="codCasaProduttrice" Type="produrre_ep" />
      <Association Name="CASA_PRODUTTRICE_produrre_film" Member="produrre_films" ThisKey="codCasaProduttrice" OtherKey="codCasaProduttrice" Type="produrre_film" />
    </Type>
  </Table>
  <Table Name="dbo.CAST" Member="CASTs">
    <Type Name="CAST">
      <Column Name="codArtista" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="cognome" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="attore" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="regista" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="nomePersonaggio" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="CAST_partecipare_ep" Member="partecipare_eps" ThisKey="codArtista" OtherKey="codArtista" Type="partecipare_ep" />
      <Association Name="CAST_partecipare_film" Member="partecipare_films" ThisKey="codArtista" OtherKey="codArtista" Type="partecipare_film" />
    </Type>
  </Table>
  <Table Name="dbo.distribuire_ep" Member="distribuire_eps">
    <Type Name="distribuire_ep">
      <Column Name="codLingua" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codEpisodio" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="EPISODIO_distribuire_ep" Member="EPISODIO" ThisKey="codEpisodio" OtherKey="codEpisodio" Type="EPISODIO" IsForeignKey="true" />
      <Association Name="LINGUA_distribuire_ep" Member="LINGUA" ThisKey="codLingua" OtherKey="codLingua" Type="LINGUA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.distribuire_film" Member="distribuire_films">
    <Type Name="distribuire_film">
      <Column Name="codLingua" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codFilm" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="FILM_distribuire_film" Member="FILM" ThisKey="codFilm" OtherKey="codFilm" Type="FILM" IsForeignKey="true" />
      <Association Name="LINGUA_distribuire_film" Member="LINGUA" ThisKey="codLingua" OtherKey="codLingua" Type="LINGUA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EPISODIO" Member="EPISODIOs">
    <Type Name="EPISODIO">
      <Column Name="codEpisodio" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="titolo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="durataComplessiva" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="vistoCensura" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="annoUscita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codiceSerie" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="numeroStagione" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="EPISODIO_VISIONE" Member="VISIONEs" ThisKey="codEpisodio" OtherKey="codEpisodio" Type="VISIONE" />
      <Association Name="EPISODIO_appartenere_ep" Member="appartenere_eps" ThisKey="codEpisodio" OtherKey="codEpisodio" Type="appartenere_ep" />
      <Association Name="EPISODIO_distribuire_ep" Member="distribuire_eps" ThisKey="codEpisodio" OtherKey="codEpisodio" Type="distribuire_ep" />
      <Association Name="EPISODIO_partecipare_ep" Member="partecipare_eps" ThisKey="codEpisodio" OtherKey="codEpisodio" Type="partecipare_ep" />
      <Association Name="EPISODIO_produrre_ep" Member="produrre_eps" ThisKey="codEpisodio" OtherKey="codEpisodio" Type="produrre_ep" />
      <Association Name="STAGIONE_EPISODIO" Member="STAGIONE" ThisKey="codiceSerie,numeroStagione" OtherKey="codiceSerie,numeroStagione" Type="STAGIONE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FILM" Member="FILMs">
    <Type Name="FILM">
      <Column Name="codFilm" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="titolo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="durataComplessiva" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="vistoCensura" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="annoUscita" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FILM_VISIONE" Member="VISIONEs" ThisKey="codFilm" OtherKey="codFilm" Type="VISIONE" />
      <Association Name="FILM_appartenere_film" Member="appartenere_films" ThisKey="codFilm" OtherKey="codFilm" Type="appartenere_film" />
      <Association Name="FILM_distribuire_film" Member="distribuire_films" ThisKey="codFilm" OtherKey="codFilm" Type="distribuire_film" />
      <Association Name="FILM_partecipare_film" Member="partecipare_films" ThisKey="codFilm" OtherKey="codFilm" Type="partecipare_film" />
      <Association Name="FILM_produrre_film" Member="produrre_films" ThisKey="codFilm" OtherKey="codFilm" Type="produrre_film" />
    </Type>
  </Table>
  <Table Name="dbo.GENERE" Member="GENEREs">
    <Type Name="GENERE">
      <Column Name="codGenere" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="descrizione" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="GENERE_appartenere_ep" Member="appartenere_eps" ThisKey="codGenere" OtherKey="codGenere" Type="appartenere_ep" />
      <Association Name="GENERE_appartenere_film" Member="appartenere_films" ThisKey="codGenere" OtherKey="codGenere" Type="appartenere_film" />
    </Type>
  </Table>
  <Table Name="dbo.LINGUA" Member="LINGUAs">
    <Type Name="LINGUA">
      <Column Name="codLingua" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lingua" Member="lingua1" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="LINGUA_distribuire_ep" Member="distribuire_eps" ThisKey="codLingua" OtherKey="codLingua" Type="distribuire_ep" />
      <Association Name="LINGUA_distribuire_film" Member="distribuire_films" ThisKey="codLingua" OtherKey="codLingua" Type="distribuire_film" />
    </Type>
  </Table>
  <Table Name="dbo.PAGAMENTO" Member="PAGAMENTOs">
    <Type Name="PAGAMENTO">
      <Column Name="codAbbonamento" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dataPagamento" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="importo" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="ABBONAMENTO_PAGAMENTO" Member="ABBONAMENTO" ThisKey="codAbbonamento" OtherKey="codAbbonamento" Type="ABBONAMENTO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.partecipare_ep" Member="partecipare_eps">
    <Type Name="partecipare_ep">
      <Column Name="codArtista" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codEpisodio" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CAST_partecipare_ep" Member="CAST" ThisKey="codArtista" OtherKey="codArtista" Type="CAST" IsForeignKey="true" />
      <Association Name="EPISODIO_partecipare_ep" Member="EPISODIO" ThisKey="codEpisodio" OtherKey="codEpisodio" Type="EPISODIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.partecipare_film" Member="partecipare_films">
    <Type Name="partecipare_film">
      <Column Name="codFilm" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codArtista" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CAST_partecipare_film" Member="CAST" ThisKey="codArtista" OtherKey="codArtista" Type="CAST" IsForeignKey="true" />
      <Association Name="FILM_partecipare_film" Member="FILM" ThisKey="codFilm" OtherKey="codFilm" Type="FILM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.produrre_ep" Member="produrre_eps">
    <Type Name="produrre_ep">
      <Column Name="codCasaProduttrice" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codEpisodio" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CASA_PRODUTTRICE_produrre_ep" Member="CASA_PRODUTTRICE" ThisKey="codCasaProduttrice" OtherKey="codCasaProduttrice" Type="CASA_PRODUTTRICE" IsForeignKey="true" />
      <Association Name="EPISODIO_produrre_ep" Member="EPISODIO" ThisKey="codEpisodio" OtherKey="codEpisodio" Type="EPISODIO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.produrre_film" Member="produrre_films">
    <Type Name="produrre_film">
      <Column Name="codCasaProduttrice" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="codFilm" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CASA_PRODUTTRICE_produrre_film" Member="CASA_PRODUTTRICE" ThisKey="codCasaProduttrice" OtherKey="codCasaProduttrice" Type="CASA_PRODUTTRICE" IsForeignKey="true" />
      <Association Name="FILM_produrre_film" Member="FILM" ThisKey="codFilm" OtherKey="codFilm" Type="FILM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SERIE" Member="SERIEs">
    <Type Name="SERIE">
      <Column Name="codiceSerie" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="titolo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="durata" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Association Name="SERIE_STAGIONE" Member="STAGIONEs" ThisKey="codiceSerie" OtherKey="codiceSerie" Type="STAGIONE" />
    </Type>
  </Table>
  <Table Name="dbo.STAGIONE" Member="STAGIONEs">
    <Type Name="STAGIONE">
      <Column Name="codiceSerie" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="numeroStagione" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="STAGIONE_EPISODIO" Member="EPISODIOs" ThisKey="codiceSerie,numeroStagione" OtherKey="codiceSerie,numeroStagione" Type="EPISODIO" />
      <Association Name="SERIE_STAGIONE" Member="SERIE" ThisKey="codiceSerie" OtherKey="codiceSerie" Type="SERIE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TITOLARE_ACCOUNT" Member="TITOLARE_ACCOUNTs">
    <Type Name="TITOLARE_ACCOUNT">
      <Column Name="CF" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nomeAccount" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="indirizzo" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="città" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="numCartaDiCredito" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="TITOLARE_ACCOUNT_ABBONAMENTO" Member="ABBONAMENTOs" ThisKey="CF" OtherKey="CF" Type="ABBONAMENTO" />
      <Association Name="ACCOUNT_TITOLARE_ACCOUNT" Member="ACCOUNT" ThisKey="nomeAccount" OtherKey="nomeAccount" Type="ACCOUNT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UTENTE" Member="UTENTEs">
    <Type Name="UTENTE">
      <Column Name="nomeAccount" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nomeUtente" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="UTENTE_VISIONE" Member="VISIONEs" ThisKey="nomeAccount,nomeUtente" OtherKey="nomeAccount,nomeUtente" Type="VISIONE" />
      <Association Name="ACCOUNT_UTENTE" Member="ACCOUNT" ThisKey="nomeAccount" OtherKey="nomeAccount" Type="ACCOUNT" IsForeignKey="true" />
    </Type>
  </Table>
</Database>